### PR TITLE
Add file ignores to bower.json

### PR DESCRIPTION
**Pull request by iDuuck**

### CODE REVIEW

**Comment by kof** [comment]
hi, you need to change x-package.json and then do make build, it will generate all the other jsons

**Comment by iDuuck** [comment]
Why, this is just for ignoring things when installing this package using `bower`.

**Comment by kof** [comment]
json files are generated by xpkg

**Comment by kof** [comment]
out of x-package.json

**Comment by kof** [comment]
bower spcific things can be defined in overlay of x-package

**Comment by iDuuck** [comment]
Oh, i see.

**Comment by iDuuck** [comment]
Any updates?

**Comment by kof** [comment]
merged

**Pull request merged**
